basePath: /api/v1
host: localhost:8080
info:
  contact: {}
  description: Backend API for Kelic Restaurant
  title: Kelic Restaurant API
  version: "1.0"
paths:
  /health:
    get:
      description: Returns 200 if the service is up
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties:
              type: string
            type: object
      summary: Health check
      tags:
      - health
swagger: "2.0"
